### ISSUE TITLE
oxe-api flask app host,port config

### ISSUE THREAD

**Issue by SteveClement** [CybersecurityLuxembourg/openxeco-core#17]
Host and port are currently not configurable (AFAIK) thus used as default.

If a user mixes up install procedures. e.g, starting with a docker container that opens port 5000 and then trying to run oxe-api outside, it will fail.

I addded a hard coded check for localhost/5000 but that is not good enough ;)

**Comment by alexisprunier** [comment]
Added the port of the server configurable. Please see the following commit:

https://github.com/CybersecurityLuxembourg/openxeco-core/commit/9ff240825aad1477681e0e21890f4fdb6053ee1e

This will be part of the v1.11.0 version.
