### ISSUE TITLE
Link to latest release in documentation

### ISSUE THREAD

**Issue by SteveClement** [CybersecurityLuxembourg/openxeco-core#28]
Currently when the release updates, say from v1.10.1 to v.1.11 the documentation needs to be manually updated.

Fix this.

https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8

Investigate, linking to something generic e.g:

https://github.com/CybersecurityLuxembourg/openxeco-core/releases/latest/download/openxeco-core-oxe-web-admin.tar.gz

currently it is:

https://github.com/CybersecurityLuxembourg/openxeco-core/releases/latest/download/openxeco-core-oxe-web-admin-v1.10.2.tar.gz

To avoid doing:

```
curl -s https://api.github.com/repos/CybersecurityLuxembourg/openxeco-core/releases/latest |jq .tag_name
"v1.10.2"
```

Then using this to build an automagic URL.

TBDisc.

**Comment by alexisprunier** [comment]
Modification applied on V1.11 branch for the next v1.11.0 version.

Links information modified to target latest docker images and packages.
GH Action to package the webapps modified to remove the version in the package name.
