### ISSUE TITLE
Refreshing the page will land you back to the login page

### ISSUE THREAD

**Issue by niumalta-tech** [CybersecurityLuxembourg/openxeco-core#36]
When you refresh any page you need to login once again.

**Comment by alexisprunier** [comment]
[46766d5](https://github.com/CybersecurityLuxembourg/openxeco-core/commit/46766d59d24c1457ecd5bb76db070293196156e5)

Fixed on admin and community webapps

Will be part of the v1.13.1 that will be created soon!
