### ISSUE TITLE
Logging in with two different accounts using the same browser causes erratic behaviour in session management

### ISSUE THREAD

**Issue by niumalta-tech** [CybersecurityLuxembourg/openxeco-core#37]
This might be related to https://github.com/CybersecurityLuxembourg/openxeco-core/issues/36 since the users are not actually doing a logout but just refreshing the page.

**Comment by alexisprunier** [comment]
You are right. We can consider that, by solving the issue [#36](https://github.com/CybersecurityLuxembourg/openxeco-core/issues/36), this one is now outdated as changing the account will necessarily require to log out first.
