### ISSUE TITLE
"Payment required error" pop up was experienced during a password reset

### ISSUE THREAD

**Issue by niumalta-tech** [CybersecurityLuxembourg/openxeco-core#38]
When resetting a password sometimes we got an error "Payment required error"

**Comment by alexisprunier** [comment]
Indeed, there was a typo in the HTTP code

[ff7bb2f](https://github.com/CybersecurityLuxembourg/openxeco-core/commit/ff7bb2fb73f63261f3cb1c4052be5e9c760930b6)

Will be part of the v1.13.1 released soon!
