### ISSUE TITLE
Closing the 'reset password' modal does not remove the data from the form

### ISSUE THREAD

**Issue by niumalta-tech** [CybersecurityLuxembourg/openxeco-core#40]
Filling in the 'reset password' form then clicking 'X' before submitting, on form reopen, data is retained unless the user navigated to another tab.

**Comment by alexisprunier** [comment]
[a6e3c91](https://github.com/CybersecurityLuxembourg/openxeco-core/commit/a6e3c91f752f3e534af2dec45ab45c3ef31fca1b)

Done for the admin and the community webapps

Will be part of the v1.13.1 that will be created soon!
