### ISSUE TITLE
Claiming an entity requires logout/login to effect change in the profile

### ISSUE THREAD

**Issue by niumalta-tech** [CybersecurityLuxembourg/openxeco-core#41]

**Comment by alexisprunier** [comment]
Hey,

Can you be more specific?

When I claim an entity on the community app, I can directly see the change here without login again. Are you talking about this?

![image](https://user-images.githubusercontent.com/8226763/187708287-ce02e78c-3855-416b-bc91-95ab75c2d399.png)

**Comment by niumalta-tech** [comment]
Will get more information @alexisprunier tried to replicate now and could not.

**Comment by alexisprunier** [comment]
Adding the content to replicate the matter:

> This is how we can replicate it:
> 
> Step 1) Open Chrome or any other browser and log in onto [community.cybersecurity.stagingcloud.co](http://community.cybersecurity.stagingcloud.co/)
> 
> Step 2) Request to claim an entity
> 
> Step 3) Log in onto the https://admin.cybersecurity.stagingcloud.co/task as INCOGNITO or use a DIFFERENT browser (due to session management conflict) and Accept the claim request by marking it as 'processed' and clicking 'Add Link' button to link the user that requested this link to the entity.
> 
> Step 4) Switch back to the user account and navigate different pages using the navbar on the left hand side then go back to the main dashboard to see 'My Entities' and you should see that the link is not updated automatically.
> 
> Step 5) log out of the user account and log back in and the link should appear in the 'My Entities' section.

**Comment by alexisprunier** [comment]
I suggested this:

[02a6934](https://github.com/CybersecurityLuxembourg/openxeco-core/commit/02a6934928d528befa95fa5a54518775c2b87754)

This way, the entities on the menu are reloaded every time the window gets the focus. If the IDs of the loaded entities are different, the state (and so, the menu) will be updated.
