### ISSUE TITLE
Uploading a favicon works, but then it fails to load on page load.

### ISSUE THREAD

**Issue by niumalta-tech** [CybersecurityLuxembourg/openxeco-core#43]
I've tried this with different .ico files from different sources.

![image](https://user-images.githubusercontent.com/67680171/188257514-1bb7c3bc-33ef-4b5b-b439-0b2e84f5ea6d.png)

**Comment by alexisprunier** [comment]
Fixed

cec530b

Will be part of the v1.13.2 and later.
