### ISSUE TITLE
Connection to oxe-api issue: getApiURL funcion not dynamic

### ISSUE THREAD

**Issue by mriccit** [CybersecurityLuxembourg/openxeco-core#63]
### Design
We designed to expose the oxe-api, oxe-web-admin, oxe-web-community as microservices in a Kubernetes Cluster so not configured in a single VM as expected by the documentation.
Furthermore the oxe-web-community has a different domain than oxe-api, oxe-web-admin. 

### Problem
We are fencing problem to connect the FE component oxe-web-admin and oxe-web-community to the BE component oxe-api due to the construction of getApiURL function in oxe-web-admin/src/utils/env.jsx & oxe-web-community/src/utils/env.jsx:

`return "https://api." + window.location.hostname.replace("www.", "").split(".").slice(1).join(".") + "/";`

### Question
Would it be possible to make this construction dynamic to define with custom values?

**Comment by alexisprunier** [comment]
Hi,

The usual way to go through is to add settings that are manageable via the the admin platform. In this case, this wouldn't work as the front-end apps require to fetch the settings, which require to know about the API endpoint.. ^^"

Here are three alternatives:

**Configure DNS redirection**

The first one would be to configure a DNS redirection. if you have your domains as such:

https://my-api.org
https://my-private-space.org

you could allow communication between the client and the API by configurating a DNS redirection as such:

api.my-private-space.org -> my-api.org

**Forked the project**

Another solution would be to fork the openXeco repository and edit the utils/env.jsx of the webapps directory (oxe-web-admin and oxe-web-community). It leads to some additional management efforts with the forked and its upstream.

**Use the "original" domain organisation**

By default, the three endpoints (admin, community and API) are organised as such to be working together:

admin.example.org
community.example.org
api.example.org

It remains to be a solution to comply to this structure.


If you have any other suggestion, I am open to hear about.

Regards

**Comment by alexisprunier** [comment]
Any update on this @mriccit ?

Thanks

**Comment by mriccit** [comment]
Hello,
thanks for the precious reply.
We are trying to follow the first the suggestion "Configure DNS redirection", if it won't work we will try to follow the "Forked the project" suggestion.

I'll let you know as soon as we have some updates or further requests.

Thanks a lot!

**Comment by alexisprunier** [comment]
I close this issue as it is.

Don't hesitate to reopen if you want to go further exploring a solution.

Regards
