### ISSUE TITLE
Request to enable private vulnerability reporting

### ISSUE THREAD

**Issue by tomausloos** [CybersecurityLuxembourg/openxeco-core#91]
Hello maintainers,

I've recently analyzed the 'openxeco-core' and 'openxeco-eccc-middleware' code and identified a few potential vulnerabilities. To make reporting these issues easier and more secure for everyone involved, I'd like to suggest enabling the private vulnerability reporting [feature](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) for these repositories. 

I'm also open to collaborating directly on fixing any confirmed vulnerabilities.

Thanks for considering this request.

**Comment by pparage** [comment]
Hello [tomausloos](https://github.com/tomausloos),
I have enabled the feature. 

Sorry for the late reply. We are thankful for you contribution.

**Comment by tomausloos** [comment]
Hi @pparage,

Thanks for the reply. 
I'll proceed to submit my findings.
